export const SSH_NEEDS_PASSWORD_MARKER = 'SSH_INTERACTIVE_PASSWORD_PROMPT_REQUESTED';
export const SSH_PRE_EXEC_PASSWORD_EVENT = 'ssh_pre_exec_password_request';
export const COMMAND_FORWARDED_TO_ACTIVE_SSH_MARKER = 'COMMAND_FORWARDED_TO_ACTIVE_SSH';
